cors:
  global:
    origins: >
      https://marketplace.dev.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.dev.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo

s3-library:
  bucket: merlot-storage-dev