cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu
    patterns:

s3-library:
  bucket: merlot-storage-demo

merlot-domain: "marketplace.demo.merlot-education.eu"